"""TRAPI QueryGraph support for CSRGraph.

Translates a TRAPI 1.6 QueryGraph into CSRGraph operations and formats the
results as a TRAPI Response ``Message``.

Supports **linear chains** (fast path via ``match_path``), **branching**
queries, and **cyclic** queries (general subgraph matcher with backtracking).

Usage::

    from csrgraph_kgx import CSRGraph
    from trapi import query

    graph = CSRGraph.load("translator_kg.csrgraph.pkl.zst", db=db)

    # One-hop: Metformin → Gene
    message = query(graph, {
        "nodes": {
            "n0": {"ids": ["CHEBI:6801"]},
            "n1": {"categories": ["biolink:Gene"]},
        },
        "edges": {
            "e0": {"subject": "n0", "object": "n1", "predicates": ["biolink:affects"]},
        },
    })

    # Two-hop: Drug → Gene → Disease
    message = query(graph, {
        "nodes": {
            "n0": {"ids": ["CHEBI:6801"]},
            "n1": {"categories": ["biolink:Gene"]},
            "n2": {"categories": ["biolink:Disease"]},
        },
        "edges": {
            "e0": {"subject": "n0", "object": "n1"},
            "e1": {"subject": "n1", "object": "n2"},
        },
    })

    # Triangle (cyclic): Drug → Gene → Disease → Drug
    message = query(graph, {
        "nodes": {
            "n0": {"ids": ["CHEBI:6801"]},
            "n1": {"categories": ["biolink:Gene"]},
            "n2": {"categories": ["biolink:Disease"]},
        },
        "edges": {
            "e0": {"subject": "n0", "object": "n1"},
            "e1": {"subject": "n1", "object": "n2"},
            "e2": {"subject": "n2", "object": "n0"},
        },
    })
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone
from typing import Iterable, Any

from csrgraph_kgx import CSRGraph, _strip_biolink

logger = logging.getLogger(__name__)

# Type alias for a complete binding of a query graph to concrete nodes/edges.
# nodes: qnode_key → CURIE,  edges: qedge_key → (subject, predicate, object)
Binding = dict[str, Any]  # {"nodes": dict[str,str], "edges": dict[str,tuple]}

# TRAPI qualifier type IDs → edge metadata field names in our backends
_QUALIFIER_TYPE_TO_FIELD: dict[str, str] = {
    "biolink:qualified_predicate": "qualified_predicate",
    "biolink:object_aspect_qualifier": "object_aspect_qualifier",
    "biolink:object_direction_qualifier": "object_direction_qualifier",
    "biolink:subject_aspect_qualifier": "subject_aspect_qualifier",
    "biolink:subject_direction_qualifier": "subject_direction_qualifier",
    "biolink:causal_mechanism_qualifier": "causal_mechanism_qualifier",
    "biolink:species_context_qualifier": "species_context_qualifier",
    "biolink:disease_context_qualifier": "disease_context_qualifier",
    "biolink:frequency_qualifier": "frequency_qualifier",
}

RESOURCE_ID = "infores:csrgraph"

#: Cap on qualifier-set combinations generated by expand_query_graph(), so a
#: deep model subtree cannot turn one constraint into thousands.
_MAX_QUALIFIER_COMBINATIONS = 64

# ---------------------------------------------------------------------------
# Symmetric predicates from Biolink Model v4.3.7
# Source: https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml
# To update: fetch biolink-model.yaml from the URL above and search for all
# slots with ``symmetric: true``.  Convert slot names to biolink: CURIEs
# (replace spaces with underscores, add ``biolink:`` prefix).
# ---------------------------------------------------------------------------
SYMMETRIC_PREDICATES: frozenset[str] = frozenset({
    "biolink:associated_with",
    "biolink:binds",
    "biolink:chemically_similar_to",
    "biolink:close_match",
    "biolink:coexists_with",
    "biolink:coexpressed_with",
    "biolink:colocalizes_with",
    "biolink:correlated_with",
    "biolink:directly_physically_interacts_with",
    "biolink:exact_match",
    "biolink:gene_fusion_with",
    "biolink:genetic_association",
    "biolink:genetic_neighborhood_of",
    "biolink:genetically_associated_with",
    "biolink:genetically_interacts_with",
    "biolink:homologous_to",
    "biolink:in_cell_population_with",
    "biolink:in_complex_with",
    "biolink:in_linkage_disequilibrium_with",
    "biolink:in_pathway_with",
    "biolink:indirectly_physically_interacts_with",
    "biolink:interacts_with",
    "biolink:negatively_correlated_with",
    "biolink:occurs_together_in_literature_with",
    "biolink:opposite_of",
    "biolink:orthologous_to",
    "biolink:overlaps",
    "biolink:paralogous_to",
    "biolink:pharmacologically_interacts_with",
    "biolink:physically_interacts_with",
    "biolink:positively_correlated_with",
    "biolink:related_condition",
    "biolink:related_to",
    "biolink:related_to_at_concept_level",
    "biolink:related_to_at_instance_level",
    "biolink:same_as",
    "biolink:similar_to",
    "biolink:temporally_related_to",
    "biolink:xenologous_to",
})


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def display_query_graph(query_graph: dict) -> str:
    """Return an ASCII visualisation of a TRAPI QueryGraph.

    Example output::

        (n0:CHEBI:6801 SmallMolecule) --[e0:affects]--> (n1:Gene)
                                      --[e1:treats]-->  (n2:Disease)
                                                        (n2:Disease) --[e2:treated_by]--> (n0:CHEBI:6801 SmallMolecule)
    """
    qnodes = query_graph["nodes"]
    qedges = query_graph["edges"]

    def _node_label(nk: str) -> str:
        qn = qnodes[nk]
        parts = [nk]
        ids = qn.get("ids")
        if ids:
            parts.append(",".join(ids[:2]))
            if len(ids) > 2:
                parts.append("...")
        cats = qn.get("categories")
        if cats:
            short = [c.replace("biolink:", "") for c in cats[:2]]
            parts.append(",".join(short))
        return ":".join(parts[:2]) + (" " + parts[2] if len(parts) > 2 else "")

    def _edge_label(ek: str) -> str:
        qe = qedges[ek]
        preds = qe.get("predicates")
        if preds:
            short = [p.replace("biolink:", "") for p in preds[:2]]
            label = ",".join(short)
            if len(preds) > 2:
                label += ",..."
        else:
            label = "*"
        quals = qe.get("qualifier_constraints", [])
        if quals:
            label += "+Q"
        return f"{ek}:{label}"

    # Group edges by subject node for compact display.
    by_subject: dict[str, list[str]] = {}
    for ek, qe in qedges.items():
        by_subject.setdefault(qe["subject"], []).append(ek)

    lines: list[str] = []
    rendered_edges: set[str] = set()

    # Render nodes that have outgoing edges.
    for subj_nk in list(by_subject.keys()):
        edge_keys = by_subject[subj_nk]
        src = f"({_node_label(subj_nk)})"
        for i, ek in enumerate(edge_keys):
            qe = qedges[ek]
            obj_nk = qe["object"]
            tgt = f"({_node_label(obj_nk)})"
            elbl = f"[{_edge_label(ek)}]"
            arrow = f" --{elbl}--> "
            if i == 0:
                lines.append(f"{src}{arrow}{tgt}")
            else:
                pad = " " * len(src)
                lines.append(f"{pad}{arrow}{tgt}")
            rendered_edges.add(ek)

    # Render any edges not yet shown (shouldn't happen, but safety net).
    for ek in qedges:
        if ek not in rendered_edges:
            qe = qedges[ek]
            src = f"({_node_label(qe['subject'])})"
            tgt = f"({_node_label(qe['object'])})"
            lines.append(f"{src} --[{_edge_label(ek)}]--> {tgt}")

    return "\n".join(lines)


def query(
    graph: CSRGraph,
    query_graph: dict,
    *,
    limit: int = 100,
    expander: BiolinkExpander | None = None,
    node_subclassing: bool = True,
    subclass_depth: int | None = 1,
) -> dict:
    """Execute a TRAPI QueryGraph against a CSRGraph and return a TRAPI Message.

    Parameters
    ----------
    graph : CSRGraph
        Graph with an attached metadata backend (``graph.db`` must be set).
    query_graph : dict
        A TRAPI 1.6 ``QueryGraph`` dict with ``nodes`` and ``edges``.
    limit : int
        Maximum number of results to return (default 100).
    expander : BiolinkExpander, optional
        When given, queried predicates and qualifier values are widened to their
        Biolink descendants before matching, so a query for ``biolink:treats``
        also answers on its descendants.  Without it, matching is literal.
    node_subclassing : bool
        Expand pinned nodes to their ``subclass_of`` descendants, so a query
        pinned to a disease also answers on its subtypes.  **On by default**,
        matching what Translator engines do: it is what lets "what treats
        Alzheimer's?" return a chemical asserted to treat a *subtype* of
        Alzheimer's.  Pass ``False`` for literal matching.
    subclass_depth : int, optional
        Subclass hops to follow.  Defaults to ``1`` (direct children only), which
        matches gandalf's ``subclass_depth=1`` so the two engines agree on the
        same graph.  Pass ``None`` to expand the hierarchy **transitively**, which
        finds more answers but diverges from engines using depth 1 — on the
        HelmsDeep ``batch_lookup`` query transitive expansion returns 524 answers
        against gandalf's 512.

    Returns
    -------
    dict
        A TRAPI ``Message`` dict with ``query_graph``, ``knowledge_graph``,
        and ``results``.
    """
    qnodes, qedges = _validate_query_graph(query_graph)
    if expander is not None:
        query_graph = expand_query_graph(query_graph, expander)
        qedges = query_graph["edges"]

    # Fast path: linearise into a chain for match_path().  Symmetric predicates
    # used to divert here to the general matcher; match_path now walks a
    # symmetric hop both ways itself, which matters because the backtracking
    # matcher is an order of magnitude slower on the same shape (26.7 s against
    # 0.33 s on the HelmsDeep two_hop_lookup).  The general matcher still owns
    # branching and cyclic queries, and keeps its own symmetric handling.
    try:
        ordered_node_keys, ordered_edge_keys, hop_dirs = _linearise(
            qnodes, qedges
        )
        bindings, truncated = _linear_query(
            graph, qnodes, qedges, ordered_node_keys, ordered_edge_keys, limit,
            hop_dirs, node_subclassing, subclass_depth,
        )
    except ValueError:
        # Branching or cyclic — use the general subgraph matcher.
        bindings, truncated = _general_match(graph, qnodes, qedges, limit)

    # Post-filter pipeline: subclass validation → node constraints →
    # edge attributes → qualifiers.
    bindings, query_ids = _resolve_subclass_bindings(
        graph, bindings, qnodes, node_subclassing, subclass_depth
    )
    bindings = _apply_node_constraint_filters(graph, bindings, qnodes)
    bindings = _apply_edge_attribute_constraints(graph, bindings, qedges)
    bindings = _apply_qualifier_filters(graph, bindings, qedges)

    return _build_message(
        graph, query_graph, bindings, query_ids, truncated=truncated, limit=limit
    )


# ──────────────────────────────────────────────────────────────────────────────
# Linear-chain fast path (delegates to match_path)
# ──────────────────────────────────────────────────────────────────────────────

def _linear_query(
    graph: CSRGraph,
    qnodes: dict[str, dict],
    qedges: dict[str, dict],
    ordered_node_keys: list[str],
    ordered_edge_keys: list[str],
    limit: int,
    hop_directions: list[bool] | None = None,
    node_subclassing: bool = False,
    subclass_depth: int | None = None,
) -> tuple[list[Binding], bool]:
    """Execute a linear-chain query via match_path and convert to bindings.

    Handles multiple IDs on the start node (BATCH expansion) and multiple
    predicates per edge (wildcard + post-filter).

    Returns ``(bindings, truncated)``.  ``match_path`` already computes whether a
    hop hit its cap; this forwards it so the caller can say so in the response
    rather than presenting a subset as if it were the whole answer.
    """
    # Determine which start IDs to iterate over (BATCH expansion).
    start_nk = ordered_node_keys[0]
    start_qn = qnodes[start_nk]
    start_ids = start_qn.get("ids") or [None]

    # Collect which edges have multiple predicates (need post-filtering).
    multi_pred_edges: dict[int, set[str]] = {}
    for hop_idx, ek in enumerate(ordered_edge_keys):
        preds = qedges[ek].get("predicates")
        if preds and len(preds) > 1:
            multi_pred_edges[hop_idx] = set(preds)

    # Symmetric predicates are direction-free: an assertion stored one way
    # answers a query posed the other way.  Each hop gets an *extra* walk in the
    # opposite direction restricted to its symmetric predicates only.
    #
    # Restricted, not the whole hop: a predicate list can mix symmetric and
    # asymmetric terms, and walking all of them backwards matched a one-way
    # ``treats`` edge in reverse whenever any symmetric predicate shared the
    # list.  With Biolink expansion this is the common case, not a corner one —
    # ``biolink:associated_with`` expands to 24 predicates of which only 8 are
    # symmetric.
    hop_extra_specs: list[tuple[str, ...] | None] = []
    for ek in ordered_edge_keys:
        sym = [p for p in (qedges[ek].get("predicates") or [])
               if p in SYMMETRIC_PREDICATES]
        hop_extra_specs.append(tuple(sym) if sym else None)

    bindings: list[Binding] = []
    truncated = False

    for start_id in start_ids:
        if len(bindings) >= limit:
            # Start IDs left unprocessed, so some batch members never ran.
            truncated = True
            break

        # Build path_spec, substituting the start ID for this iteration.
        path_spec = _build_path_spec(
            ordered_node_keys, ordered_edge_keys, qnodes, qedges,
            start_id_override=start_id,
        )
        # The nodes match_path started this iteration from, so a path can be
        # anchored at its known end regardless of how each edge is oriented.
        start_set: set[str] | None = None
        if start_id is not None and start_id in graph.node_to_id:
            if node_subclassing:
                start_set = {
                    graph.nodes[i] for i in graph._expand_subclasses(
                        graph.node_to_id[start_id], subclass_depth
                    )
                }
            else:
                start_set = {start_id}

        remaining = limit - len(bindings)
        raw_paths, stats = graph.match_path(
            path_spec, limit=remaining, hop_directions=hop_directions,
            hop_extra_specs=hop_extra_specs,
            node_subclassing=node_subclassing, subclass_depth=subclass_depth,
            return_stats=True,
        )
        truncated = truncated or stats.truncated

        for path in raw_paths:
            nodes: dict[str, str] = {}
            edges: dict[str, tuple] = {}

            if path:
                dirs = hop_directions or [True] * len(path)
                # Walk the chain by shared endpoint rather than by hop
                # direction.  Direction alone is wrong once a hop can also be
                # walked the other way for its symmetric predicates: such an
                # edge comes back in true (subject, predicate, object) order,
                # which is the *opposite* of what the hop's direction implies,
                # and reading it by direction swapped the two endpoints — a
                # query pinned to one gene returned the other one bound in its
                # place.
                first_subj, _, first_obj = path[0]
                if start_set is not None:
                    cur = first_subj if first_subj in start_set else first_obj
                else:
                    # Open start node: nothing to anchor on, so fall back to the
                    # declared direction.
                    cur = first_subj if dirs[0] else first_obj
                nodes[ordered_node_keys[0]] = cur
                for hop_idx, (subj, _, obj) in enumerate(path):
                    nxt = obj if subj == cur else subj
                    nodes[ordered_node_keys[hop_idx + 1]] = nxt
                    cur = nxt

            # Post-filter: check multi-predicate edges.
            skip = False
            for hop_idx, ek in enumerate(ordered_edge_keys):
                if hop_idx < len(path):
                    subj, pred, obj = path[hop_idx]
                    if hop_idx in multi_pred_edges:
                        if pred not in multi_pred_edges[hop_idx]:
                            skip = True
                            break
                    edges[ek] = path[hop_idx]
            if skip:
                continue

            bindings.append({"nodes": nodes, "edges": edges})
            if len(bindings) >= limit:
                break

    return bindings, truncated


class BiolinkExpander:
    """Widens queried predicates and qualifier values to their Biolink descendants.

    A TRAPI query for ``biolink:treats`` is asking about the whole ``treats``
    subtree, so an edge asserted as ``biolink:applied_to_treat`` is a valid answer.
    Matching predicates literally therefore *under*-reports: on the HelmsDeep
    corpus it cost one answer on ``mvp1_light`` (``CHEBI:135939``, which reaches
    Alzheimer's by ``applied_to_treat``) and most of the MVP2 qualifier results.

    This is deliberately a plain mapping rather than a hard Biolink Model Toolkit
    dependency, since running without BMT — and without fetching a schema at
    import time — is a property of this library worth keeping. Supply the maps
    yourself, or build them from BMT when it is installed:

        expander = BiolinkExpander.from_bmt()          # needs `pip install bmt`
        trapi.query(graph, qg, expander=expander)

    With no expander, matching stays literal and behaviour is unchanged.
    """

    def __init__(
        self,
        predicates: dict[str, frozenset[str]] | None = None,
        qualifier_values: dict[str, frozenset[str]] | None = None,
    ) -> None:
        self.predicates = predicates or {}
        self.qualifier_values = qualifier_values or {}

    def expand_predicate(self, predicate: str) -> frozenset[str]:
        """*predicate* plus its descendants; just itself when unknown."""
        return self.predicates.get(predicate) or frozenset({predicate})

    def expand_qualifier_value(self, value: str) -> frozenset[str]:
        return self.qualifier_values.get(value) or frozenset({value})

    @classmethod
    def from_bmt(
        cls,
        predicates: Iterable[str] | None = None,
        qualifier_values: Iterable[str] | None = None,
        biolink_version: str | None = None,
    ) -> BiolinkExpander:
        """Build the maps from the Biolink Model Toolkit.

        Only the terms given are resolved, because walking the whole model is slow
        and a server only needs the terms its callers actually use. Pass the
        predicates and qualifier values your traffic contains; unlisted terms fall
        back to literal matching.

        Pin *biolink_version* to whatever produced the graph, so expansion and
        data agree.
        """
        try:
            from bmt import Toolkit  # type: ignore[import]
        except ImportError:
            raise ImportError(
                "BiolinkExpander.from_bmt() needs the Biolink Model Toolkit: "
                "pip install bmt"
            ) from None

        tk = Toolkit(schema=biolink_version) if biolink_version else Toolkit()

        pred_map: dict[str, frozenset[str]] = {}
        for p in predicates or ():
            try:
                if tk.get_element(p) is None:
                    continue
                desc = tk.get_descendants(p, formatted=True) or []
            except Exception:
                continue
            pred_map[p] = frozenset({p, *desc})

        try:
            enum_names = list(tk.view.all_enums().keys())
        except Exception:
            enum_names = []

        qual_map: dict[str, frozenset[str]] = {}
        for v in qualifier_values or ():
            found: set[str] = {v}
            # Qualifier values are enum permissible values, so resolve them
            # through the enums only.  Falling back to get_element() here looks
            # tempting but is wrong: a value like "activity" also names the
            # Biolink *class* ``Activity``, and that returns class descendants
            # (ClinicalTrial, Study, ...) which can never match a qualifier.
            for enum_name in enum_names:
                try:
                    if tk.is_permissible_value_of_enum(enum_name=enum_name, value=v):
                        found.update(
                            tk.get_permissible_value_descendants(
                                permissible_value=v, enum_name=enum_name
                            ) or []
                        )
                except Exception:
                    continue
            qual_map[v] = frozenset(found)

        return cls(pred_map, qual_map)


def expand_query_graph(query_graph: dict, expander: BiolinkExpander) -> dict:
    """Return a copy of *query_graph* widened to Biolink descendants.

    Rewriting the query up front means the rest of the engine needs no changes:
    predicate lists simply get longer, and each qualifier set is replaced by the
    combinations of its widened values — TRAPI already treats multiple
    ``qualifier_constraints`` as alternatives, so that preserves the semantics.
    """
    import itertools

    edges: dict[str, dict] = {}
    for ek, qe in (query_graph.get("edges") or {}).items():
        new_qe = dict(qe)

        preds = qe.get("predicates")
        if preds:
            widened: list[str] = []
            for p in preds:
                for d in sorted(expander.expand_predicate(p)):
                    if d not in widened:
                        widened.append(d)
            new_qe["predicates"] = widened

        qcs = qe.get("qualifier_constraints")
        if qcs:
            new_qcs: list[dict] = []
            seen: set[tuple] = set()
            for qc in qcs:
                qset = qc.get("qualifier_set") or []
                choices = [
                    [
                        {"qualifier_type_id": q.get("qualifier_type_id"),
                         "qualifier_value": v}
                        for v in sorted(
                            expander.expand_qualifier_value(q.get("qualifier_value"))
                        )
                    ]
                    for q in qset
                ]
                # Cap the cross-product: a pathological model subtree should not
                # turn one constraint into thousands.
                total = 1
                for c in choices:
                    total *= max(1, len(c))
                if total > _MAX_QUALIFIER_COMBINATIONS:
                    new_qcs.append(qc)
                    continue
                for combo in itertools.product(*choices) if choices else []:
                    key = tuple(
                        (q["qualifier_type_id"], q["qualifier_value"]) for q in combo
                    )
                    if key not in seen:
                        seen.add(key)
                        new_qcs.append({"qualifier_set": list(combo)})
            if new_qcs:
                new_qe["qualifier_constraints"] = new_qcs

        edges[ek] = new_qe

    out = dict(query_graph)
    out["edges"] = edges
    return out


def _validate_query_graph(query_graph: dict) -> tuple[dict, dict]:
    """Check a QueryGraph's shape and return ``(nodes, edges)``.

    Without this, structurally invalid input surfaced as whatever internal
    ``KeyError`` happened to fire first — an edge naming a nonexistent node came
    out as ``KeyError: 'n_missing'`` from deep inside linearisation. Raising
    :class:`ValueError` here gives callers a usable message, and
    ``trapi_server`` already turns that into a 400.
    """
    if not isinstance(query_graph, dict):
        raise ValueError("query_graph must be an object")

    nodes = query_graph.get("nodes")
    edges = query_graph.get("edges")
    if not isinstance(nodes, dict):
        raise ValueError("query_graph.nodes must be an object")
    if not isinstance(edges, dict):
        # Pathfinder-style graphs carry `paths` instead of `edges`; say so
        # rather than reporting a missing key.
        if "paths" in query_graph:
            raise ValueError(
                "query_graph uses 'paths' (Pathfinder); only 'edges' is supported"
            )
        raise ValueError("query_graph.edges must be an object")

    for ek, qe in edges.items():
        if not isinstance(qe, dict):
            raise ValueError(f"edge {ek!r} must be an object")
        for end in ("subject", "object"):
            ref = qe.get(end)
            if ref is None:
                raise ValueError(f"edge {ek!r} is missing {end!r}")
            if ref not in nodes:
                raise ValueError(
                    f"edge {ek!r} {end} {ref!r} is not a node in the query graph"
                )
    return nodes, edges


def _linearise(
    qnodes: dict[str, dict],
    qedges: dict[str, dict],
) -> tuple[list[str], list[str], list[bool]]:
    """Convert a QueryGraph into an ordered linear chain of node/edge keys.

    Returns ``(nodes, edges, directions)``.  ``directions[i]`` is ``True`` when hop
    *i* is traversed along the edge (subject -> object) and ``False`` when it is
    traversed against it, which happens whenever the chain is anchored at an
    edge's object end -- the "what treats disease X?" shape.  Dropping this flag
    silently produced empty results for every such query.

    Raises ``ValueError`` for disconnected, branching, or cyclic query graphs.
    """
    adj: dict[str, list[tuple[str, str, bool]]] = {nk: [] for nk in qnodes}
    for ek, qe in qedges.items():
        subj, obj = qe["subject"], qe["object"]
        adj[subj].append((ek, obj, True))
        adj[obj].append((ek, subj, False))

    def _start_score(nk: str) -> tuple[int, int]:
        has_ids = 0 if qnodes[nk].get("ids") else 1
        return (has_ids, len(adj[nk]))

    start = min(qnodes, key=_start_score)

    ordered_nodes: list[str] = [start]
    ordered_edges: list[str] = []
    directions: list[bool] = []
    visited_edges: set[str] = set()
    visited_nodes: set[str] = {start}

    current = start
    while True:
        next_hop = None
        for ek, nbr, is_fwd in adj[current]:
            if ek not in visited_edges and nbr not in visited_nodes:
                next_hop = (ek, nbr, is_fwd)
                break
        if next_hop is None:
            break
        ek, nbr, is_fwd = next_hop
        visited_edges.add(ek)
        visited_nodes.add(nbr)
        ordered_edges.append(ek)
        ordered_nodes.append(nbr)
        directions.append(is_fwd)
        current = nbr

    if len(ordered_nodes) != len(qnodes) or len(ordered_edges) != len(qedges):
        raise ValueError("Non-linear query graph")

    return ordered_nodes, ordered_edges, directions


# ──────────────────────────────────────────────────────────────────────────────
# General subgraph matcher (handles branching and cyclic queries)
# ──────────────────────────────────────────────────────────────────────────────

def _general_match(
    graph: CSRGraph,
    qnodes: dict[str, dict],
    qedges: dict[str, dict],
    limit: int,
) -> tuple[list[Binding], bool]:
    """Find all subgraph bindings matching an arbitrary query graph pattern.

    Returns ``(bindings, truncated)``; *truncated* is True when the search
    stopped because *limit* was reached, so a caller can tell an exhaustive
    answer from a partial one.

    Uses backtracking search:
    1. Pick the most constrained unbound QNode adjacent to a bound QNode.
    2. Enumerate candidate CURIEs by traversing edges from bound neighbors.
    3. Verify all edges between the candidate and already-bound QNodes.
    4. Recurse until all QNodes are bound, or backtrack.

    For cycles, step 3 catches edges between two already-bound nodes and
    verifies they exist in the data graph.
    """
    # Build query-graph adjacency: qnode_key → [(qedge_key, neighbor_qnode_key)]
    adj: dict[str, list[tuple[str, str]]] = {nk: [] for nk in qnodes}
    for ek, qe in qedges.items():
        adj[qe["subject"]].append((ek, qe["object"]))
        adj[qe["object"]].append((ek, qe["subject"]))

    db = graph._require_db()

    # Pick start node: prefer pinned ids, then most edges (most constrained).
    def _start_score(nk: str) -> tuple[int, int]:
        has_ids = 0 if qnodes[nk].get("ids") else 1
        return (has_ids, -len(adj[nk]))

    start_key = min(qnodes, key=_start_score)
    start_candidates = _get_candidates(graph, db, qnodes[start_key])
    if not start_candidates:
        return [], False

    results: list[Binding] = []
    # Set when the search stops because *limit* was reached, so the caller can
    # tell a complete answer from a truncated one.  match_path reports the same
    # thing via MatchStats; this matcher previously reported nothing at all.
    truncated = False

    def _backtrack(
        node_bindings: dict[str, str],
        edge_bindings: dict[str, tuple],
    ) -> None:
        if len(results) >= limit:
            return

        # All nodes bound — record result.
        if len(node_bindings) == len(qnodes):
            # Verify any remaining unverified edges (cycles).
            for ek, qe in qedges.items():
                if ek not in edge_bindings:
                    s_curie = node_bindings[qe["subject"]]
                    o_curie = node_bindings[qe["object"]]
                    preds = _matching_predicates(graph, qe, s_curie, o_curie)
                    if not preds:
                        return
                    edge_bindings[ek] = (s_curie, preds[0], o_curie)
            results.append({
                "nodes": dict(node_bindings),
                "edges": dict(edge_bindings),
            })
            return

        # Pick next unbound QNode: must be adjacent to at least one bound QNode.
        # Prefer nodes with pinned ids, then most constrained (most bound neighbors).
        next_key = None
        best_score = (2, 0)  # (no_ids, -bound_neighbors)
        for nk in qnodes:
            if nk in node_bindings:
                continue
            bound_nbrs = sum(
                1 for _, nbr in adj[nk] if nbr in node_bindings
            )
            if bound_nbrs == 0:
                continue
            has_ids = 0 if qnodes[nk].get("ids") else 1
            score = (has_ids, -bound_nbrs)
            if score < best_score:
                best_score = score
                next_key = nk

        if next_key is None:
            # Disconnected component — shouldn't happen if the query is connected.
            return

        # Gather candidates: intersect neighbors from all bound adjacent QNodes.
        candidate_sets: list[set[str]] = []
        connecting_edges: list[tuple[str, str, bool]] = []  # (ek, bound_nk, is_forward)

        for ek, nbr in adj[next_key]:
            if nbr not in node_bindings:
                continue
            qe = qedges[ek]
            is_forward = (qe["subject"] == nbr)
            connecting_edges.append((ek, nbr, is_forward))

            bound_curie = node_bindings[nbr]
            if is_forward:
                # nbr is subject, next_key is object: get outgoing neighbors of nbr
                nbrs = _get_edge_neighbors(graph, qe, bound_curie, forward=True)
            else:
                # nbr is object, next_key is subject: get nodes that point TO nbr
                # Since our graph is directed (subject→object), next_key→nbr
                nbrs = _get_edge_neighbors(graph, qe, bound_curie, forward=False)
            candidate_sets.append(set(nbrs))

        if not candidate_sets:
            return

        # Intersect all candidate sets.
        candidates = candidate_sets[0]
        for cs in candidate_sets[1:]:
            candidates &= cs
            if not candidates:
                return

        # Filter candidates by QNode constraints.
        #
        # ``sorted``, not ``list``: *candidates* is a set of CURIE **strings**,
        # and Python randomises ``str.__hash__`` per process, so ``list(...)``
        # yields a different order on every run.  That order decides which
        # candidates are explored before ``len(results) >= limit`` stops the
        # search, so an identical query returned different answers run to run —
        # measured on the HelmsDeep ``two_hop_lookup`` as three different genes
        # across three runs, and stable under ``PYTHONHASHSEED=0``.
        #
        # ``match_path`` never had this problem because it works in CSR index
        # space, where the sets hold ``int`` node indices and ``int.__hash__``
        # is identity.  Sorting by CURIE rather than node index is deliberate:
        # index order depends on KGX ingest order, so it would not survive a
        # graph rebuild, whereas CURIEs do.
        candidates = _filter_by_qnode(graph, db, qnodes[next_key], sorted(candidates))

        for curie in candidates:
            if len(results) >= limit:
                nonlocal truncated
                truncated = True
                return
            # Bind this node and all connecting edges.
            node_bindings[next_key] = curie
            new_edges: list[str] = []
            valid = True
            for ek, bound_nk, is_forward in connecting_edges:
                qe = qedges[ek]
                if is_forward:
                    s, o = node_bindings[bound_nk], curie
                else:
                    s, o = curie, node_bindings[bound_nk]
                preds = _matching_predicates(graph, qe, s, o)
                if not preds:
                    valid = False
                    break
                edge_bindings[ek] = (s, preds[0], o)
                new_edges.append(ek)

            if valid:
                _backtrack(node_bindings, edge_bindings)

            # Undo bindings (backtrack).
            del node_bindings[next_key]
            for ek in new_edges:
                edge_bindings.pop(ek, None)

    # Launch search from each start candidate.
    for curie in start_candidates:
        if len(results) >= limit:
            # Start candidates left unexplored: the answer is a subset.
            truncated = True
            break
        _backtrack({start_key: curie}, {})

    if truncated:
        logger.warning(
            "_general_match stopped at limit=%d: returning %d binding(s), which "
            "is a subset of the matches. Raise limit= for a complete result.",
            limit, len(results),
        )
    return results, truncated


def _get_candidates(
    graph: CSRGraph,
    db: Any,
    qnode: dict,
) -> list[str]:
    """Return candidate CURIEs for a QNode."""
    ids = qnode.get("ids")
    if ids:
        return [c for c in ids if c in graph.node_to_id]

    categories = qnode.get("categories")
    if categories:
        matched = db.filter_nodes(
            list(graph.node_to_id.keys()),
            category=categories[0],
        )
        return [m["id"] for m in matched if m["id"] in graph.node_to_id]

    # Unconstrained — cannot enumerate all nodes. Return empty.
    return []


def _filter_by_qnode(
    graph: CSRGraph,
    db: Any,
    qnode: dict,
    candidates: list[str],
) -> list[str]:
    """Filter candidate CURIEs by QNode ids, categories, and constraints."""
    if not candidates:
        return []

    ids = qnode.get("ids")
    if ids:
        id_set = set(ids)
        candidates = [c for c in candidates if c in id_set]

    categories = qnode.get("categories")
    if categories and candidates:
        # OR across multiple categories.
        matched_ids: set[str] = set()
        for cat in categories:
            matched = db.filter_nodes(candidates, category=cat)
            matched_ids.update(m["id"] for m in matched)
        candidates = [c for c in candidates if c in matched_ids]

    # Apply node constraints.
    constraints = qnode.get("constraints")
    if constraints and candidates:
        candidates = _apply_node_constraints(db, candidates, constraints)

    return candidates


def _get_edge_neighbors(
    graph: CSRGraph,
    qedge: dict,
    source_curie: str,
    forward: bool,
) -> list[str]:
    """Get neighbor CURIEs reachable from source_curie along a QEdge.

    When forward=True, source is the subject; we return objects.
    When forward=False, source is the object; we look for nodes that have
    edges pointing TO source (i.e., source is the object, we need subjects).

    For symmetric predicates, both directions are searched automatically.
    """
    predicates = qedge.get("predicates")
    has_symmetric = predicates and any(p in SYMMETRIC_PREDICATES for p in predicates)

    if forward:
        result: set[str] = set()
        if predicates:
            for pred in predicates:
                result.update(graph.neighbors(source_curie, relation=pred))
        else:
            result.update(graph.neighbors(source_curie))
        # Symmetric: also get reverse neighbors (nodes pointing TO source).
        if has_symmetric:
            result.update(_reverse_neighbors(graph, source_curie, predicates))
        return list(result)

    # Reverse direction.
    result_set = set(_reverse_neighbors(graph, source_curie, predicates))
    # Symmetric: also get forward neighbors.
    if has_symmetric:
        if predicates:
            for pred in predicates:
                result_set.update(graph.neighbors(source_curie, relation=pred))
        else:
            result_set.update(graph.neighbors(source_curie))
    return list(result_set)


def _reverse_neighbors(
    graph: CSRGraph,
    target_curie: str,
    predicates: list[str] | None,
) -> list[str]:
    """Find nodes with edges pointing TO target_curie (reverse lookup)."""
    if target_curie not in graph.node_to_id:
        return []
    v = graph.node_to_id[target_curie]

    result: set[str] = set()
    relations_to_check = (
        [_strip_biolink(p) for p in predicates]
        if predicates else list(graph.csr_by_relation.keys())
    )
    for rel in relations_to_check:
        csr = graph.csr_by_relation.get(rel)
        if csr is None:
            continue
        col = csr.getcol(v)
        for u in col.nonzero()[0]:
            result.add(graph.nodes[int(u)])
    return list(result)


def _matching_predicates(
    graph: CSRGraph,
    qedge: dict,
    source: str,
    target: str,
) -> list[str]:
    """Return predicates of actual edges from source→target that match QEdge.

    For symmetric predicates, also checks the reverse direction (target→source).
    """
    actual_preds = graph.edges_between(source, target)

    allowed = qedge.get("predicates")
    symmetric_allowed = {p for p in (allowed or []) if p in SYMMETRIC_PREDICATES}

    # Reverse-direction edges count only for the symmetric predicates.  Taking
    # every reverse edge whenever *any* allowed predicate was symmetric matched
    # one-way edges backwards: a query for [treats, interacts_with] returned a
    # stored ``C treats D`` as though ``D treats C``.
    if symmetric_allowed:
        reverse_preds = [
            p for p in graph.edges_between(target, source)
            if p in symmetric_allowed
        ]
        # Sorted for the same reason as the candidate set: callers take
        # ``preds[0]`` as *the* predicate for the edge binding, so iterating a
        # string set here made which predicate got reported vary between runs
        # even when nothing was truncated.
        actual_preds = sorted(set(actual_preds) | set(reverse_preds))

    if not actual_preds:
        return []

    if allowed:
        allowed_set = set(allowed)
        return [p for p in actual_preds if p in allowed_set]

    return actual_preds


# ──────────────────────────────────────────────────────────────────────────────
# Path-spec construction (for linear fast path)
# ──────────────────────────────────────────────────────────────────────────────

def _qnode_to_spec(qnode: dict) -> str | dict | None:
    """Convert a QNode to a match_path NodeSpec."""
    ids = qnode.get("ids")
    if ids and len(ids) == 1:
        return ids[0]

    categories = qnode.get("categories")
    if categories:
        return {"category": categories[0]}

    if ids and len(ids) > 1:
        return ids[0]

    return None


def _qedge_to_spec(qedge: dict, is_forward: bool) -> str | dict | None:
    """Convert a QEdge to a match_path EdgeSpec.

    Multiple predicates → wildcard (None); post-filtered in _linear_query.
    attribute_constraints are handled by _apply_edge_attribute_constraints
    post-filter, NOT embedded in the EdgeSpec.
    """
    predicates = qedge.get("predicates")

    if not predicates:
        return None                      # wildcard
    if len(predicates) == 1:
        return predicates[0]
    # Hand the whole set to match_path so it filters during traversal.  Returning
    # a wildcard here and post-filtering afterwards silently lost answers: the
    # result cap filled with whichever predicates happened to come first, so a
    # selective predicate in the set could end up with nothing.
    return tuple(predicates)


def _build_path_spec(
    ordered_node_keys: list[str],
    ordered_edge_keys: list[str],
    qnodes: dict[str, dict],
    qedges: dict[str, dict],
    start_id_override: str | None = None,
) -> list:
    """Build a match_path path_spec from the linearised query chain."""
    spec: list = []
    for i, nk in enumerate(ordered_node_keys):
        if i == 0 and start_id_override is not None:
            spec.append(start_id_override)
        else:
            spec.append(_qnode_to_spec(qnodes[nk]))
        if i < len(ordered_edge_keys):
            ek = ordered_edge_keys[i]
            qe = qedges[ek]
            is_forward = (qe["subject"] == nk)
            spec.append(_qedge_to_spec(qe, is_forward))
    return spec


# ──────────────────────────────────────────────────────────────────────────────
# Node constraint post-filtering (applied to bindings from both paths)
# ──────────────────────────────────────────────────────────────────────────────

def _apply_node_constraint_filters(
    graph: CSRGraph,
    bindings: list[Binding],
    qnodes: dict[str, dict],
) -> list[Binding]:
    """Post-filter bindings by QNode constraints."""
    # Collect nodes with constraints.
    constrained: dict[str, list[dict]] = {}
    for nk, qn in qnodes.items():
        cs = qn.get("constraints")
        if cs:
            constrained[nk] = cs

    if not constrained:
        return bindings

    db = graph._require_db()
    filtered: list[Binding] = []

    for binding in bindings:
        keep = True
        for nk, constraints in constrained.items():
            curie = binding["nodes"].get(nk)
            if curie is None:
                keep = False
                break
            meta = db.get_node(curie)
            for c in constraints:
                if not _eval_constraint(meta, c):
                    keep = False
                    break
            if not keep:
                break
        if keep:
            filtered.append(binding)

    return filtered


# ──────────────────────────────────────────────────────────────────────────────
# Constraint evaluation (node constraints + edge attribute_constraints)
# ──────────────────────────────────────────────────────────────────────────────

def _apply_node_constraints(
    db: Any,
    candidates: list[str],
    constraints: list[dict],
) -> list[str]:
    """Filter candidates by TRAPI AttributeConstraint list (ANDed)."""
    result = candidates
    for constraint in constraints:
        if not result:
            break
        result = [c for c in result if _eval_constraint(db.get_node(c), constraint)]
    return result


def _eval_constraint(meta: dict, constraint: dict) -> bool:
    """Evaluate a single TRAPI AttributeConstraint against metadata.

    Supports operators: ``==``, ``>``, ``<``, ``matches`` (regex), ``in``.
    The ``not`` flag negates the result.
    """
    field = constraint.get("id", "")
    # Strip biolink: prefix for metadata field lookup.
    field_name = field.replace("biolink:", "") if field.startswith("biolink:") else field
    operator = constraint.get("operator", "==")
    expected = constraint.get("value")
    negate = constraint.get("not", False)

    actual = meta.get(field_name)

    result = _eval_operator(actual, operator, expected)
    return (not result) if negate else result


def _eval_operator(actual: Any, operator: str, expected: Any) -> bool:
    """Evaluate a comparison operator."""
    if actual is None:
        return False

    if operator == "==":
        # For lists, acts like SQL IN (any element matches).
        if isinstance(actual, list):
            return expected in actual
        return str(actual) == str(expected)

    if operator == "===":
        return actual == expected

    if operator == ">":
        try:
            return float(actual) > float(expected)
        except (TypeError, ValueError):
            return False

    if operator == "<":
        try:
            return float(actual) < float(expected)
        except (TypeError, ValueError):
            return False

    if operator == "matches":
        # Value is a regex pattern, possibly with /pattern/flags syntax.
        pattern = str(expected)
        flags = 0
        if pattern.startswith("/"):
            # Parse /pattern/flags format.
            last_slash = pattern.rfind("/")
            if last_slash > 0:
                flag_str = pattern[last_slash + 1:]
                pattern = pattern[1:last_slash]
                if "i" in flag_str:
                    flags = re.IGNORECASE
        target = str(actual) if not isinstance(actual, list) else " ".join(str(v) for v in actual)
        try:
            return bool(re.search(pattern, target, flags))
        except re.error:
            return False

    if operator == "in":
        # Check if expected value is contained in actual (list or string).
        if isinstance(actual, list):
            return expected in actual
        return str(expected) in str(actual)

    return False


def _apply_edge_attribute_constraints(
    graph: CSRGraph,
    bindings: list[Binding],
    qedges: dict[str, dict],
) -> list[Binding]:
    """Post-filter bindings by QEdge attribute_constraints."""
    constrained: dict[str, list[dict]] = {}
    for ek, qe in qedges.items():
        acs = qe.get("attribute_constraints", [])
        if acs:
            constrained[ek] = acs

    if not constrained:
        return bindings

    db = graph._require_db()
    filtered: list[Binding] = []

    for binding in bindings:
        keep = True
        for ek, constraints in constrained.items():
            edge = binding["edges"].get(ek)
            if edge is None:
                keep = False
                break
            subj, pred, obj = edge
            # The same triple can be stored several times with different
            # qualifiers/attributes; the constraint is met if *any* of those
            # variants meets it.  Reading a single record silently dropped
            # answers whose matching variant was not the one kept.
            variants = db.get_edge_variants(subj, pred, obj) or [{}]
            if not any(
                all(_eval_constraint(v, ac) for ac in constraints)
                for v in variants
            ):
                keep = False
                break
        if keep:
            filtered.append(binding)

    return filtered


# ──────────────────────────────────────────────────────────────────────────────
# Qualifier post-filtering
# ──────────────────────────────────────────────────────────────────────────────

def _apply_qualifier_filters(
    graph: CSRGraph,
    bindings: list[Binding],
    qedges: dict[str, dict],
) -> list[Binding]:
    """Post-filter bindings by QEdge qualifier_constraints."""
    # Collect edges with qualifier constraints.
    constrained_edges: dict[str, list[list[dict]]] = {}
    for ek, qe in qedges.items():
        qcs = qe.get("qualifier_constraints", [])
        if qcs:
            constrained_edges[ek] = [qc["qualifier_set"] for qc in qcs]

    if not constrained_edges:
        return bindings

    db = graph._require_db()
    filtered: list[Binding] = []

    for binding in bindings:
        keep = True
        for ek, qualifier_sets in constrained_edges.items():
            edge = binding["edges"].get(ek)
            if edge is None:
                keep = False
                break
            subj, pred, obj = edge
            variants = db.get_edge_variants(subj, pred, obj) or [{}]
            if not any(
                _matches_any_qualifier_set(v, qualifier_sets) for v in variants
            ):
                keep = False
                break
        if keep:
            filtered.append(binding)

    return filtered


def _matches_any_qualifier_set(
    edge_meta: dict,
    qualifier_sets: list[list[dict]],
) -> bool:
    """OR across qualifier sets."""
    return any(_matches_qualifier_set(edge_meta, qs) for qs in qualifier_sets)


def _matches_qualifier_set(edge_meta: dict, qualifiers: list[dict]) -> bool:
    """AND within a qualifier set."""
    for q in qualifiers:
        qtype = q.get("qualifier_type_id", "")
        qval = q.get("qualifier_value", "")
        field = _QUALIFIER_TYPE_TO_FIELD.get(qtype)
        if field is None:
            return False
        actual = edge_meta.get(field)
        if actual is None or str(actual) != str(qval):
            return False
    return True


# ──────────────────────────────────────────────────────────────────────────────
# TRAPI response assembly (works with bindings from both paths)
# ──────────────────────────────────────────────────────────────────────────────

def _resolve_subclass_bindings(
    graph: CSRGraph,
    bindings: list[Binding],
    qnodes: dict[str, dict],
    node_subclassing: bool,
    subclass_depth: int | None,
) -> tuple[list[Binding], dict[str, dict[str, str]]]:
    """Validate subclass-expanded bindings and record what each was queried as.

    ``match_path`` expands a pinned node to its ``subclass_of`` descendants and
    binds the descendant directly, and nothing downstream re-examined it.  Two
    consequences, both measured on the HelmsDeep ``batch_lookup`` query:

    * **The descendant never faced the QNode's ``categories``.** This graph
      asserts ``HP:x subclass_of MONDO:y``, so a query pinned to diseases *and
      constrained to* ``biolink:Disease`` bound six ``PhenotypicFeature`` nodes
      (``HP:0000978`` "Easy Bruising" among them).  Those answers contradict the
      query, which is worse than missing ones, so they are dropped here.
    * **A descendant is not the CURIE the caller asked for.** TRAPI says so with
      ``NodeBinding.query_id``; without it a client cannot distinguish a subtype
      match from a direct hit.  The returned map supplies it.

    Only the *expanded* CURIEs are checked, not every bound node: open nodes were
    already category-filtered during enumeration, so re-validating them would add
    a large batched backend call per query node and find nothing.
    """
    if not bindings:
        return bindings, {}

    db = graph.db
    query_ids: dict[str, dict[str, str]] = {}
    drop: dict[str, set[str]] = {}

    for nk, qn in qnodes.items():
        ids = qn.get("ids")
        if not ids or not node_subclassing:
            continue
        bound = {b["nodes"][nk] for b in bindings if nk in b["nodes"]}
        expanded = bound - set(ids)
        if not expanded:
            continue

        # Which queried CURIE did each descendant come from?  Expand the same
        # way match_path did so the two agree.
        mapping: dict[str, str] = {}
        for qid in ids:
            if qid not in graph.node_to_id:
                continue
            for i in graph._expand_subclasses(graph.node_to_id[qid], subclass_depth):
                curie = graph.nodes[i]
                if curie in expanded:
                    mapping.setdefault(curie, qid)
        if mapping:
            query_ids[nk] = mapping

        categories = qn.get("categories")
        if categories:
            ok: set[str] = set()
            for cat in categories:
                ok.update(
                    m["id"] for m in db.filter_nodes(sorted(expanded), category=cat)
                )
            bad = expanded - ok
            if bad:
                drop[nk] = bad

    if drop:
        bindings = [
            b for b in bindings
            if not any(b["nodes"].get(k) in bad for k, bad in drop.items())
        ]

    return bindings, query_ids


def _build_message(
    graph: CSRGraph,
    query_graph: dict,
    bindings: list[Binding],
    query_ids: dict[str, dict[str, str]] | None = None,
    *,
    truncated: bool = False,
    limit: int | None = None,
) -> dict:
    """Assemble a TRAPI Message from bindings.

    When *truncated*, a ``message.logs`` entry records that the result set is a
    subset.  A client cannot otherwise distinguish "these are all the answers"
    from "these are the first *limit* of them", and the two mean very different
    things: with constraints applied after the cap, a constrained query can
    return far fewer answers than exist.
    """
    db = graph.db
    kg_nodes: dict[str, dict] = {}
    kg_edges: dict[str, dict] = {}
    # Map each distinct (subject, predicate, object) to a stable, unique edge
    # id.  A delimiter-joined string ("subj-pred-obj") is unsafe because CURIEs
    # and predicates contain hyphens, so distinct edges could collide and
    # overwrite each other; keying on the tuple avoids that entirely.
    edge_id_by_tuple: dict[tuple[str, str, str], str] = {}
    results: list[dict] = []

    for binding in bindings:
        node_bindings: dict[str, list[dict]] = {}
        edge_bindings: dict[str, list[dict]] = {}

        for nk, curie in binding["nodes"].items():
            nb: dict[str, Any] = {"id": curie, "attributes": []}
            # A subclass-expanded node is not the CURIE that was asked for, so
            # say which one it stands in for.
            queried = (query_ids or {}).get(nk, {}).get(curie)
            if queried is not None:
                nb["query_id"] = queried
            node_bindings[nk] = [nb]
            if curie not in kg_nodes:
                kg_nodes[curie] = _make_kg_node(db, curie)

        for ek, edge_tuple in binding["edges"].items():
            subj, pred, obj = edge_tuple
            key = (subj, pred, obj)
            edge_id = edge_id_by_tuple.get(key)
            if edge_id is None:
                edge_id = f"e{len(edge_id_by_tuple)}"
                edge_id_by_tuple[key] = edge_id
                kg_edges[edge_id] = _make_kg_edge(db, subj, pred, obj)
            edge_bindings[ek] = [{"id": edge_id, "attributes": []}]

        results.append({
            "node_bindings": node_bindings,
            "analyses": [{
                "resource_id": RESOURCE_ID,
                "edge_bindings": edge_bindings,
            }],
        })

    message: dict[str, Any] = {
        "query_graph": query_graph,
        "knowledge_graph": {
            "nodes": kg_nodes,
            "edges": kg_edges,
        },
        "results": results,
    }
    if truncated:
        message["logs"] = [{
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "level": "WARNING",
            "code": "ResultsTruncated",
            "message": (
                f"Result set is incomplete: enumeration stopped at limit="
                f"{limit}, returning {len(results)} result(s). Raise the limit "
                f"for a complete answer."
            ),
        }]
    return message


def _make_kg_node(db: Any, curie: str) -> dict:
    """Create a TRAPI KnowledgeGraph Node from metadata."""
    node: dict[str, Any] = {"categories": [], "attributes": []}
    if db is not None:
        meta = db.get_node(curie)
        if meta:
            node["name"] = meta.get("name")
            cats = meta.get("category", [])
            if isinstance(cats, str):
                cats = [cats]
            node["categories"] = cats
            for k, v in meta.items():
                if k not in ("id", "name", "category"):
                    node["attributes"].append({
                        "attribute_type_id": f"biolink:{k}" if ":" not in k else k,
                        "value": v,
                    })
    return node


def _make_kg_edge(db: Any, subj: str, pred: str, obj: str) -> dict:
    """Create a TRAPI KnowledgeGraph Edge from metadata."""
    edge: dict[str, Any] = {
        "subject": subj,
        "predicate": pred or "biolink:related_to",
        "object": obj,
        "sources": [{
            "resource_id": RESOURCE_ID,
            "resource_role": "primary_knowledge_source",
        }],
        "attributes": [],
    }
    if db is not None:
        meta = db.get_edge(subj, pred, obj)
        if meta:
            if meta.get("knowledge_level"):
                edge["attributes"].append({
                    "attribute_type_id": "biolink:knowledge_level",
                    "value": meta["knowledge_level"],
                })
            if meta.get("agent_type"):
                edge["attributes"].append({
                    "attribute_type_id": "biolink:agent_type",
                    "value": meta["agent_type"],
                })
            qualifiers = []
            for qfield, qtype_id in [
                ("qualified_predicate", "biolink:qualified_predicate"),
                ("object_aspect_qualifier", "biolink:object_aspect_qualifier"),
                ("object_direction_qualifier", "biolink:object_direction_qualifier"),
                ("subject_aspect_qualifier", "biolink:subject_aspect_qualifier"),
                ("subject_direction_qualifier", "biolink:subject_direction_qualifier"),
                ("causal_mechanism_qualifier", "biolink:causal_mechanism_qualifier"),
            ]:
                val = meta.get(qfield)
                if val:
                    qualifiers.append({
                        "qualifier_type_id": qtype_id,
                        "qualifier_value": str(val),
                    })
            if qualifiers:
                edge["qualifiers"] = qualifiers
            skip = {
                "subject", "predicate", "object",
                "knowledge_level", "agent_type",
                "qualified_predicate",
                "object_aspect_qualifier", "object_direction_qualifier",
                "subject_aspect_qualifier", "subject_direction_qualifier",
                "causal_mechanism_qualifier",
            }
            for k, v in meta.items():
                if k not in skip:
                    edge["attributes"].append({
                        "attribute_type_id": f"biolink:{k}" if ":" not in k else k,
                        "value": v,
                    })
    return edge
